services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=lecture'
      - 'MYSQL_PASSWORD=root'
      - 'MYSQL_ROOT_PASSWORD=root'
      - 'MYSQL_USER=user'
    ports:
      - '3306:3306'
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 1024M

